backend:
  name: github
  repo: romarr/fabb # Path to your GitHub repository
  branch: master # Branch to update (optional; defaults to master)
  base_url: https://rsoauth.herokuapp.com

publish_mode: editorial_workflow
media_folder: "img/uploads" # Media files will be stored in the repo under images/uploads

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Articles" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Mis en avant", name: "featured", widget: "boolean", default: "false"}
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Catégorie", name: "categories", widget: "string"}
      - {label: "Modèle", name: "modele", widget: "string"}
      - {label: "Date de publication", name: "date", widget: "datetime"}
      - {label: "Id Vidéo", name: "video", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}